version: "3.8"

services:
  pgdb:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDADA: /data/postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    expose:
      - 5432:5432
  fastapi:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/fastapi_tz
    ports:
      - "8001:8000"

    restart: always
    env_file:
      - db/.env
    depends_on:
      - pgdb
volumes:
  data: