"""Migrate

Revision ID: 4cc79648f96a
Revises: 
Create Date: 2024-04-22 01:11:20.224098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc79648f96a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('ordid', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('ordid')
    )
    op.create_table('testing',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numbeer', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('orders_done', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['orders'], ['orders.ordid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier')
    op.drop_table('testing')
    op.drop_table('orders')
    # ### end Alembic commands ###
