"""Last revision

Revision ID: f7db388a6659
Revises: 710da0f95a39
Create Date: 2024-04-24 02:59:17.443447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7db388a6659'
down_revision: Union[str, None] = '710da0f95a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'time',
               existing_type=sa.DATE(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'time',
               existing_type=sa.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
